### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by janrg** [dpyeates/magvar#1]
Hi,
Thanks for creating this library. I was very happy to find it since https://github.com/naturalatlas/geomagnetism apparently isn't being maintained anymore. I wanted to use magvar in a TypeScript project and was trying to write a type definition for it but unfortunately, as far as I can tell, the singleton pattern usage makes it impossible to write a type definition without modifying the source file.
Would you consider accepting a PR that modifies your code (possibly converting it to TypeScript) if that means the way the library is imported is slightly changed?

**Comment by janrg** [comment]
I started doing a fork but in the process noticed that with the code you've already written it was trivial to also output the other parameters of the geomagnetic field, so I created a new package https://github.com/janrg/wmm-geomagnetic that also provides TS typings (of course acknowledging that the whole thing is derived from this package).
While doing that I noticed some transcription errors in the coefficients, so I created a pull request correcting these:
https://github.com/dpyeates/magvar/pull/3

**Comment by dpyeates** [comment]
Merged and I have bumped to version 1.0.3. Thanks.
