### ISSUE TITLE
Integrity for CDN use

### ISSUE THREAD

**Issue by brettz9** [dpyeates/magvar#2]
Could you perhaps add SHA integrity values for your npm releases so they can be used in the browser with the `integrity` attribute with CDNs like unpkg? Thanks!

**Comment by dpyeates** [comment]
Added package-lock.json

**Comment by brettz9** [comment]
I was looking for integrity SHA's of your distribution files, not just the dependencies; see https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity for more details on how this is used.

**Comment by dpyeates** [comment]
So you are not using npm but using magyar.js direct from a browser? The integrity value for magvar.js is:

sha384-h8j3kasvixrHZJX5PkbvSsyLsdZ08nAUfP82apqcRR6HZbGn10z/0P5ayW4s4JwB%

Run by the command 'cat magvar.js  | openssl dgst -sha384 -binary | openssl base64 -A'

**Comment by brettz9** [comment]
Ah, ok, good to know, thanks! And yes,for use in a browser... I guess this can be closed AFAIC.
